### ISSUE TITLE
Destination and Source Callback-Delays are not shown

### ISSUE THREAD

**Issue by Tobias-Pe** [tier4/CARET_analyze#292]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [X] I've confirmed the issue is certainly related to this repository. If not, please consider to make a new issue in https://github.com/tier4/caret/issues

### Description

`read_arch.get_path('<target_path>').verify()` returns True, so Caret_analysze confirmed that it should understand the **whole** path.
In my scenario it doesnt show the whole path.

How it is:
![image](https://user-images.githubusercontent.com/49952224/236528125-10cd7333-e62b-441d-a0cf-a16af5b85682.png)

How it should be like:
![image](https://user-images.githubusercontent.com/49952224/236531047-b8094704-eedb-4b7c-b3a0-bde227b68c47.png)

Here you can find my setup (notebook, architecturefile and trace data): https://ufile.io/p5ua9ble

**Comment by nabetetsu** [comment]
@Tobias-Pe Thank you for repoting the issue.
Unfortunately I cannot download setup files you uploaded to ufile site. Could you attach the zip file directly to this thread ?

**Comment by Tobias-Pe** [comment]
> [issue.zip](https://github.com/tier4/CARET_analyze/files/11419354/issue.zip) ah didnt know i can just paste it here ^^

@nabetetsu

**Comment by nabetetsu** [comment]
@Tobias-Pe Sorry for the delay in my response.
Thanks to the data you gave us, we now know where the problem lies.
The issue is handled on this PR: https://github.com/tier4/CARET_analyze/pull/293

**Comment by atsushi421** [comment]
@Tobias-Pe 
Hi.
The PRs for the changes have been merged, so if you update the repository and run the following zip file, it should draw the figure you are looking for.
[issue_resolved.zip](https://github.com/tier4/CARET_analyze/files/11648604/issue_resolved.zip)

The meaning of the following codes in the zip file can be found on [this page](https://tier4.github.io/CARET_doc/latest/configuration/inter_node_data_path/#considering-firstlast-callback).
```
camera_to_motor.include_first_callback = True
camera_to_motor.include_last_callback = True
```

**Comment by atsushi421** [comment]
@Tobias-Pe 
Just a gentle reminder.

**Comment by Tobias-Pe** [comment]
Great! I can confirm that it works now 🎉 

![image](https://github.com/tier4/CARET_analyze/assets/49952224/26d956bf-1ba9-413d-80bf-ca0320d8e225)


In this scenario it still works the same:

![image](https://github.com/tier4/CARET_analyze/assets/49952224/37f8c7ef-2a64-4988-a2f2-2a35a712c4d4)
