### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Autostone-c** [tier4/caret_analyze#407]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [X] I've confirmed the issue is certainly related to this repository. If not, please consider to make a new issue in https://github.com/tier4/caret/issues

### Description

hi, when i am analyzing data on another machine. I have encountered the following error
![image](https://github.com/tier4/caret_analyze/assets/50130211/1c4b89fd-7d0a-49b9-a426-fa1a96958282)

**Comment by Autostone-c** [comment]
> ### Checklist
> * [x]  I've read the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
> * [x]  I've confirmed the issue is certainly related to this repository. If not, please consider to make a new issue in https://github.com/tier4/caret/issues
> 
> ### Description
> hi, when i am analyzing data on another machine. I have encountered the following error ![image](https://user-images.githubusercontent.com/50130211/277848691-1c4b89fd-7d0a-49b9-a426-fa1a96958282.png)

i guess my record file has no data. but i run it as follow 
#one terminal
source /autoware_path/install/setup.bash
source ros2_caret_ws/install/local_setup.bash
export LD_PRELOAD=$(readlink -f ~/ros2_caret_ws/install/caret_trace/lib/libcaret.so)

#another terminal
source /autoware_path/install/setup.bash
source ros2_caret_ws/install/local_setup.bash
ros2 caret record --light

why record file has no data

**Comment by ymski** [comment]
Hi @Autostone-c 
There seems to be no trace data, are you able to measure as documented? `source` order can be a problem.
Also, please check if tracing is enabled with the following command.
```
source ~/ros2_caret_ws/install/local_setup.bash
ros2 run tracetools status
```

If you have checked the above mentioned and tracing is still not available, please follow the community guidelines and submit an issue to https://github.com/tier4/caret.
